<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Insert</name>
   <tag></tag>
   <elementGuidId>cc8e165a-a503-47d8-9710-d4503775d294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[2]/div[2]/app-event-management-layout/div/div[2]/div/app-event-management-list/p-panel/div/div[2]/div[1]/div/div/p-datatable/div/div[1]/p-header/div/button/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[2]/div[2]/app-event-management-layout/div/div[2]/div/app-event-management-list/p-panel/div/div[2]/div[1]/div/div/p-datatable/div/div[1]/p-header/div/button/span[1]</value>
   </webElementProperties>
</WebElementEntity>
