<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Sort</name>
   <tag></tag>
   <elementGuidId>90bb03fd-c210-4e92-90a5-96619afcfb21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]//app-body//app-event-categories-management-layout//app-event-categories-management-list/p-panel//p-datatable//table/thead/tr/th[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]//app-body//app-event-categories-management-layout//app-event-categories-management-list/p-panel//p-datatable//table/thead/tr/th[2]</value>
   </webElementProperties>
</WebElementEntity>
