<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Update</name>
   <tag></tag>
   <elementGuidId>0c974490-c315-4b92-a7f5-ee0ac69ddee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]//app-event-categories-management-list/p-panel//p-datatable//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]//app-event-categories-management-list/p-panel//p-datatable//button</value>
   </webElementProperties>
</WebElementEntity>
