<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Insert</name>
   <tag></tag>
   <elementGuidId>a428507f-362a-4011-b642-8336080e95f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body//app-event-categories-management-layout//app-event-categories-management-list/p-panel//p-datatable//p-header//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body//app-event-categories-management-layout//app-event-categories-management-list/p-panel//p-datatable//p-header//button</value>
   </webElementProperties>
</WebElementEntity>
