<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Clear</name>
   <tag></tag>
   <elementGuidId>64c9e64c-1eb1-499e-928f-59f39a260911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body//app-event-categories-management-layout//app-event-categories-management-search-fields//button[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body//app-event-categories-management-layout//app-event-categories-management-search-fields//button[2]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
