<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Back</name>
   <tag></tag>
   <elementGuidId>000cfbe8-4219-4857-8a52-163ddabaeab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body//app-event-categories-management-details//div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body//app-event-categories-management-details//div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
