<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Page</name>
   <tag></tag>
   <elementGuidId>ff7416e4-7381-4f4c-afde-a485a839c648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[1]/app-side-bar/div/nav/ul/div[4]/div/div/li/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[1]/app-side-bar/div/nav/ul/div[4]/div/div/li/ul/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
