<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_NextPage</name>
   <tag></tag>
   <elementGuidId>d6dc0d40-87a3-4d4e-ad5d-5228b7719f52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]//app-body//div[2]/app-event-categories-management-layout//app-event-categories-management-list/p-panel//p-datatable//p-paginator/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]//app-body//div[2]/app-event-categories-management-layout//app-event-categories-management-list/p-panel//p-datatable//p-paginator/div/a[3]</value>
   </webElementProperties>
</WebElementEntity>
