<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NE_EventGroupManagement</name>
   <tag></tag>
   <elementGuidId>92b65e10-4719-4d3f-9b38-2fafab5308fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[1]/app-side-bar/div/div/div/nav/ul/div[4]/div/div/li/ul/li[1]/a/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[1]/app-side-bar/div/div/div/nav/ul/div[4]/div/div/li/ul/li[1]/a/span[1]</value>
   </webElementProperties>
</WebElementEntity>
