<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NE_EventManagement</name>
   <tag></tag>
   <elementGuidId>e87fd875-6798-4ac6-b1e4-bced8de6f4e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[1]/app-side-bar/div/nav/ul/div[4]/div/div/li/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[1]/app-side-bar/div/nav/ul/div[4]/div/div/li/ul/li[2]/a</value>
   </webElementProperties>
</WebElementEntity>
