<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NE_SideMenu</name>
   <tag></tag>
   <elementGuidId>a06baceb-d1ad-4631-a135-45fd429c3a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[1]/app-side-bar/div/div/div/nav/ul/div[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[1]/app-side-bar/div/div/div/nav/ul/div[4]/div/a</value>
   </webElementProperties>
</WebElementEntity>
