<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_No</name>
   <tag></tag>
   <elementGuidId>8a1dc396-db4b-4ee4-b526-3080abaff43c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='app-form']/div/app-body/div/div/div[2]/div[2]/app-event-categories-management-layout/div/p-confirmdialog/div/div[3]/button[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-clickable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-form&quot;)/div[@class=&quot;ui-grid ui-grid-responsive&quot;]/app-body[1]/div[@class=&quot;ui-grid ui-grid-responsive&quot;]/div[@class=&quot;ui-grid-row&quot;]/div[@class=&quot;ui-grid-col-10&quot;]/div[2]/app-event-categories-management-layout[1]/div[@class=&quot;ui-grid ui-grid-responsive&quot;]/p-confirmdialog[@class=&quot;ng-tns-c10-1&quot;]/div[@class=&quot;ng-tns-c10-1 ui-dialog ui-confirmdialog ui-widget ui-widget-content ui-corner-all ui-shadow ng-trigger ng-trigger-dialogState&quot;]/div[@class=&quot;ui-dialog-footer ui-widget-content ng-tns-c10-1&quot;]/button[@class=&quot;ng-tns-c10-1 ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left&quot;]/span[@class=&quot;ui-button-text ui-clickable&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//section[@id='app-form']/div/app-body/div/div/div[2]/div[2]/app-event-categories-management-layout/div/p-confirmdialog/div/div[3]/button[2]/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to delete this record?'])[1]/following::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//button[2]/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
